version: "3.7"

services:
  dev:
    image: dev
    build:
      context: .
      args:
        - USER
        - njobs=6
    hostname: docker
    environment:
      - TERM
      - DISPLAY
      - http_proxy
      - https_proxy
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.gitconfig:${HOME}/.gitconfig:ro"
      - "${HOME}/.ssh:${HOME}/.ssh:ro"

# vim: set expandtab shiftwidth=0 tabstop=2 :
